spring:
  application:
    name: backendservice
  kafka:
    bootstrap-servers: localhost:9092
#    todo: посмотреть на необходимость
    consumer:
      properties:
        spring.json.trusted.packages: '*'

  datasource:
    url: jdbc:postgresql://localhost:5432/maintenancedb
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
      hibernate:
        ddl-auto: update
